apiVersion: apps/v1
kind: Deployment
metadata:
  name: team
  namespace: team
spec:
  replicas: 2
  selector:
    matchLabels:
      app: team
  template:
    metadata:
      labels:
        app: team
    spec:
      containers:
      - name: hello-kubernetes
        image: liorkamrat/hello-arc:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: myconfig-map